image: Visual Studio 2019

install:
  - ps: Install-Product node 12

build_script:
  - cmd: fake.cmd

test: off

artifacts:
  - path: bin
    name: bin

for:
-
  branches:
    only:
      - master

  artifacts:
  - path: temp/*.nupkg