// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FSharpx.Collections")>]
[<assembly: AssemblyProductAttribute("FSharpx.Collections")>]
[<assembly: AssemblyDescriptionAttribute("FSharpx.Collections is a collection of datastructures for use with F# and C#.")>]
[<assembly: InternalsVisibleToAttribute("FSharpx.Collections.Tests")>]
[<assembly: InternalsVisibleToAttribute("FSharpx.Collections.Experimental.Tests")>]
[<assembly: AssemblyVersionAttribute("3.1.0")>]
[<assembly: AssemblyFileVersionAttribute("3.1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "FSharpx.Collections"

    [<Literal>]
    let AssemblyProduct = "FSharpx.Collections"

    [<Literal>]
    let AssemblyDescription =
        "FSharpx.Collections is a collection of datastructures for use with F# and C#."

    [<Literal>]
    let InternalsVisibleTo = "FSharpx.Collections.Tests"

    [<Literal>]
    let InternalsVisibleTo_1 = "FSharpx.Collections.Experimental.Tests"

    [<Literal>]
    let AssemblyVersion = "3.1.0"

    [<Literal>]
    let AssemblyFileVersion = "3.1.0"

    [<Literal>]
    let AssemblyConfiguration = "Release"
