// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FSharpx.Collections.Experimental")>]
[<assembly: AssemblyProductAttribute("FSharpx.Collections")>]
[<assembly: AssemblyDescriptionAttribute("FSharpx.Collections is a collection of datastructures for use with F# and C#.")>]
[<assembly: InternalsVisibleToAttribute("FSharpx.Collections.Tests")>]
[<assembly: InternalsVisibleToAttribute("FSharpx.Collections.Experimental.Tests")>]
[<assembly: AssemblyVersionAttribute("3.0.1")>]
[<assembly: AssemblyFileVersionAttribute("3.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpx.Collections.Experimental"
    let [<Literal>] AssemblyProduct = "FSharpx.Collections"
    let [<Literal>] AssemblyDescription = "FSharpx.Collections is a collection of datastructures for use with F# and C#."
    let [<Literal>] InternalsVisibleTo = "FSharpx.Collections.Tests"
    let [<Literal>] InternalsVisibleTo_1 = "FSharpx.Collections.Experimental.Tests"
    let [<Literal>] AssemblyVersion = "3.0.1"
    let [<Literal>] AssemblyFileVersion = "3.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
