name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release NuGet package'
        required: true
        default: false
        type: boolean

permissions:
  id-token: write

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [8.0.416]
        node: ['24']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
    - name: setup git config
      run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/paket.lock') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Install local tools
      run: dotnet tool restore
    - name: Paket Restore
      run: dotnet paket restore
    - name: Build and Test
      run: dotnet run --project build/build.fsproj

    - name: Obtain NuGet key
      # this hash is v1.1.0
      uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544
      id: login
      with:
          user: dsyme
    - name: Publish NuGet to NuGet.org
      if: matrix.os == 'windows-latest' && github.ref == 'refs/heads/master' && github.event.inputs.release == 'true'
      run: dotnet run --project build/build.fsproj -- Release
      env:
        NUGET_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}

